-- The ramen rating data collection comes from kaggle.com/datasets/ankanhore545/top-ramen-ratings-2022 
-- containing reviews of various ramen from all over the world

-- Create table and Loaded data into SQL
CREATE TABLE TOPRAMENRATINGS (REVIEW int, 
							  BRAND VARCHAR(255),
							  VARIETY VARCHAR(255),
							  STYLE VARCHAR(255),
							  COUNTRY VARCHAR(255),
							  STARS VARCHAR(255)
							 )

-- Checked the first ten rows
SELECT *
FROM TOPRAMENRATINGS
LIMIT 10

-- Checked Total Data
SELECT COUNT (*) AS TOTAL_DATA
FROM TOPRAMENRATINGS

-- DATA CLEANING --
-- Identifying Duplicate Entries and Reviews
SELECT BRAND,
	VARIETY,
	STYLE,
	COUNTRY,
	COUNT(*) AS DUPLICATE_COUNT
FROM TOPRAMENRATINGS
GROUP BY BRAND,
	VARIETY,
	STYLE,
	COUNTRY
HAVING COUNT(*) > 1
ORDER BY DUPLICATE_COUNT DESC

-- Execution of Duplicate Entries and Reviews
DELETE
FROM TOPRAMENRATINGS
WHERE REVIEW IN
		(SELECT REVIEW
			FROM
				(SELECT REVIEW,
						ROW_NUMBER() OVER(PARTITION BY BRAND,
										  VARIETY,
										  STYLE,
										  COUNTRY
										  ORDER BY REVIEW DESC) AS ROW_NUM
					FROM TOPRAMENRATINGS) T
			WHERE T.ROW_NUM > 1 )

-- Identifying Unrated Ramen Products
SELECT *
FROM TOPRAMENRATINGS
WHERE STARS IN ('Unrated','NS','NR')

-- Identifying Fractional Star Ratings
SELECT *
FROM TOPRAMENRATINGS
WHERE STARS LIKE '%/%'

-- Execution of Fractional Star Ratings
UPDATE TOPRAMENRATINGS
SET STARS = CAST(SPLIT_PART(STARS, '/',1) AS DECIMAL(3,2))
WHERE STARS LIKE '%/%'

-- ANALYSIS --
-- Determined the 75th percentile
-- SELECT PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY VARIETY_COUNT) AS PERCENTILE_75
-- FROM
-- 	(SELECT BRAND,
-- 			COUNT(VARIETY) AS VARIETY_COUNT
-- 		FROM TOPRAMENRATINGS
-- 		GROUP BY BRAND) AS SUBQUERY
-- Top-rated Brand Ramen
SELECT BRAND,
	ROUND(AVG(CASE
			  WHEN STARS IN ('NS','NR','Unrated') THEN NULL
			  ELSE CAST(STARS AS FLOAT)
			  END)::NUMERIC,
		2) AS STARS
FROM TOPRAMENRATINGS
GROUP BY BRAND
HAVING COUNT(DISTINCT VARIETY) > 5
ORDER BY STARS DESC
LIMIT 10

-- The Most Diverse Brand
SELECT BRAND,
	COUNT(DISTINCT VARIETY) AS VARIETY
FROM TOPRAMENRATINGS
GROUP BY BRAND
ORDER BY VARIETY DESC
LIMIT 10

-- The Most Diverse Country
SELECT COUNTRY,
	COUNT(DISTINCT VARIETY) AS VARIETY
FROM TOPRAMENRATINGS
GROUP BY COUNTRY
ORDER BY VARIETY DESC
LIMIT 10

-- Variety Popularity 
SELECT VARIETY,
	COUNT(VARIETY) AS VARIETY_COUNT
FROM TOPRAMENRATINGS
GROUP BY VARIETY
ORDER BY VARIETY_COUNT DESC
LIMIT 10

-- Most Commonly Produced Packaging Style
SELECT STYLE,
	COUNT(*) AS VARIETY_COUNT
FROM TOPRAMENRATINGS
GROUP BY STYLE
ORDER BY VARIETY_COUNT DESC
